<div id="m2-component" data-bind="scope:'m2kocomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#m2-component": {
        "Magento_Ui/js/core/app": {
           "components": {
                "m2kocomponent": {
                    "component": "Magento_Theme/js/m2kocomponent",
                    "template" : "Magento_Theme/m2kocomponent-template"
                }
            }
        }
    }
}
</script>
