<?php
    $banner_image_1 = $block->getData('banner_image_1');
    $banner_image_2 = $block->getData('banner_image_2');

?>

<div class="row mt-3">
    <div class="col-lg-6 col-sm-12">
        <img src="<?php echo $block->getViewFileUrl("Magento_Theme::images/$banner_image_1"); ?>"/>
    </div>
    <div class="col-lg-6 col-sm-12">
        <img src="<?php echo $block->getViewFileUrl("Magento_Theme::images/$banner_image_2"); ?>"/>
    </div>
</div>