<div class="news_wrapper">
    <div class="container-fluid">
        <div class="list_product_header have_tab">
            <p class="list_product_title main_title">News</p>
            <ul class="list_product_tab">
                <li>Review Product</li>
                <li>Tips & Tricks</li>
                <li>Promotions</li>
                <li>View all</li>
            </ul>
        </div>
        <div class="col-12">
            <div class="news_wrapper_item">
                <div class="item">
                    <div class="news_image">
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/news_01.jpg'); ?>"/>
                    </div>   
                    <div class="news_info">
                        <p class="news_title">How To Make A Fresh Juice Blended For Your Family?</p>
                        <span class="news_label">Organic</span>
                    </div>
                </div>
                <div class="item">
                    <div class="news_image">
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/news_02.jpg'); ?>"/>
                    </div>   
                    <div class="news_info">
                        <p class="news_title">How To Make A Fresh Juice Blended For Your Family?</p>
                        <span class="news_label">Organic</span>
                    </div>
                </div>
                <div class="item">
                    <div class="news_image">
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/news_03.jpg'); ?>"/>
                    </div>   
                    <div class="news_info">
                        <p class="news_title">How To Make A Fresh Juice Blended For Your Family?</p>
                        <span class="news_label">Organic</span>
                    </div>
                </div>
                <div class="item">
                    <div class="news_image">
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/news_04.jpg'); ?>"/>
                    </div>   
                    <div class="news_info">
                        <p class="news_title">How To Make A Fresh Juice Blended For Your Family?</p>
                        <span class="news_label">Organic</span>
                    </div>
                </div>
                <div class="item">
                    <div class="news_image">
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/news_01.jpg'); ?>"/>
                    </div>   
                    <div class="news_info">
                        <p class="news_title">How To Make A Fresh Juice Blended For Your Family?</p>
                        <span class="news_label">Organic</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>