<?php 
    $main_title = $block->getData("main_title");
    $products_array = $block->getData("products_array");
    $is_have_tab = $block->getData("is_have_tab");
    $is_full_info = $block->getData("is_full_info");
    $is_only_image = $block->getData("is_only_image");
    $css_have_tab = $is_have_tab ? "have_tab" : "not_tab";
    $css_full_info = $is_full_info ? "" : "not_full_info";
    $css_only_image = $is_only_image ? "only_image" : "";
    $list_tab = $block->getData("list_tab");
    // dd($products_array);
?>
<div class="list_product_header <?= $css_have_tab ?>">
    <p class="list_product_title main_title"><?= $main_title ?></p>
    <ul class="list_product_tab">
        <?php
            if($list_tab){
            foreach ($list_tab as $key => $tab_item) {
                    echo "<li> $tab_item </li>";
                } 
            }
        ?>
    </ul>
</div>
<h1 class="main_title"></h1>
<div class="row wrap_item">
    <div class="col-12">
        <div class="product_list_wrapper <?= $css_only_image ?>">
    <?php 
    
    foreach ($products_array as $key => $product_item) : 
        $product_image = $product_item['product_image'] ? $product_item['product_image'] : "";
        $product_name = $product_item['product_name'] ? $product_item['product_name'] : "";
        $total_rate = $product_item['total_rate'] ? $product_item['total_rate'] : "";
        $old_price = $product_item['old_price'] ? $product_item['old_price'] : "";
        $new_price = $product_item['new_price'] ? $product_item['new_price'] : "";
        $discount_percent = $product_item['discount_percent'] ? $product_item['discount_percent'] : "";
        $name_of_discount_1 = $product_item['name_of_discount_1'] ? $product_item['name_of_discount_1'] : "";
        $name_of_discount_2 = $product_item['name_of_discount_2'] ? $product_item['name_of_discount_2'] : "";    
    
    ?>
            <div class="item">
                <div class="product_image">
                    <img src="<?php echo $block->getViewFileUrl("Magento_Theme::images/$product_image"); ?>"/>
                </div>   
                    <p class="product_title"><?= $product_name ?></p>
                <div class="product_info <?= $css_full_info ?>">
                    <div class="product_rate">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg>
                        <span class="product_total_rate"><?= $total_rate ?></span>
                    </div>
                    <p class="product_old_price"><?= $old_price ?></p>
                    <div class="product_discount_name">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                        </svg>
                        <span><?= $name_of_discount_1 ?></span>
                    </div>
                    <div class="product_discount_name">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                            <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                        </svg>
                        <span><?= $name_of_discount_2 ?></span>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="product_price"><?= $new_price ?></span>
                        <span class="product_discount_percent"><?= $discount_percent ?></span>
                    </div>
                </div>
            </div>
    <?php endforeach; ?>
        </div>
    </div>
</div>
    

   